# Generated by Django 3.2.16 on 2022-12-19 22:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_article_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
