# Generated by Django 3.2.16 on 2023-03-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='NoSettedNickname', max_length=20, unique=True),
        ),
    ]
