# Generated by Django 3.2.16 on 2022-12-31 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0002_auto_20221228_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymouscomment',
            old_name='username',
            new_name='writer',
        ),
    ]
